apiVersion: v1
kind: Namespace
metadata:
  name: resilience
  labels:
    app.kubernetes.io/part-of: distributed-cyber-resilience
---
apiVersion: v1
kind: Namespace
metadata:
  name: resilience-lab
  labels:
    app.kubernetes.io/part-of: distributed-cyber-resilience
